name: labour_management
description: Labour management system
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: 0.5.7+3
  cupertino_icons: 0.1.3
  fluttertoast: 4.0.1
  shimmer: 1.1.1
  curved_navigation_bar: 0.3.3
  dio: 3.0.8
  http: 0.12.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/drawables/login_bg.jpg
    - assets/drawables/logo_black.png
    - assets/drawables/logo_white.png
  fonts:
    - family: libreBarcode
      fonts:
        - asset: assets/fonts/Libre_Barcode_39_Text/LibreBarcode39Text-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf